name: Test

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, "latest"]

    steps:
      - uses: actions/checkout@v4

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: npm install, build, lint, and test
        run: |
          npm i
          npm run lint
          npm run build
